name: DB Calculator

on:
  workflow_dispatch:
    inputs:
      calculate:
        type: choice
        description: What to calculate between X and Y
        required: true
        options: 
        - source
        - destination
      source:
        type: string
        description: The volume of a sound at its source in dbA
        required: true
      destination:
        type: string
        description: The volume of a sound at its destination in dbA
        required: true
      distance:
        type: string
        description: The distance between source and destination in meters
        required: true
  

permissions:
  contents: read

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Calculate volume at source
      if: ${{ inputs.calculate }} == "source"
      run: |
        python -m decibel_calc.py --calculate source --source ${{ inputs.source }} --destination ${{ inputs.destination }}  --distance ${{ inputs.distance }}

    - name: Calculate volume at destination
      if: ${{ inputs.calculate }} == "destination"
      run: |
        python -m decibel_calc.py --calculate destination --source ${{ inputs.source }} --destination ${{ inputs.destination }}  --distance ${{ inputs.distance }}