name: DB Calculator

on:
  workflow_dispatch:
    inputs:
      calculate:
        type: choice
        description: What to calculate between X and Y
        required: true
        options: 
        - source
        - destination
      source:
        type: string
        description: The volume of a sound at its source in dbA
        required: False
        default: "0"
      destination:
        type: string
        description: The volume of a sound at its destination in dbA
        required: False
        default: "0"
      distance:
        type: string
        description: The distance between source and destination in meters
        required: true
  

permissions:
  contents: read

jobs:
  run-calculation1:
    if: ${{ inputs.calculate }} == 'source'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Calculate volume at source
      run: |
        python decibel_calc.py --calculate source --source ${{ inputs.source }} --destination ${{ inputs.destination }}  --distance ${{ inputs.distance }}

  run-calculation2:
    if: ${{ inputs.calculate }} == 'destination'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Calculate volume at destination
      run: |
        python decibel_calc.py --calculate destination --source ${{ inputs.source }} --destination ${{ inputs.destination }}  --distance ${{ inputs.distance }}